import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { QuizContainer } from "@/components/Quiz/QuizContainer";
import {UserPanel} from "@/components/User/UserPanel";
import {useStore} from "@/store";
import {useEffect, useState} from "react";
import {ArtistAlbumType} from "@/api/artists/types";
import {getArtists} from "@/api/artists";

export default function Home() {
    const [albums, setAlbums] = useState<ArtistAlbumType[]>([]);
    const user = useStore((state) => state.user)

    useEffect(() => {
        if (!user) {
            return setAlbums([])
        }
        const fetchAlbums = async () => {
            try {
                const response = await getArtists();
                setAlbums(response.data.albums)
            } catch (e) {
                console.log(e);
            }
        }
        fetchAlbums()
    }, [user]);

    return (
    <>
      <Head>
        <title>Beatles Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>
            <UserPanel  />
            {albums.length > 0 && <QuizContainer albums={albums} />}
        </main>
      </div>
    </>
  );
}
